---
- hosts: ansible-server
  become: true

  tasks:
          - name: create docker image using war file
            command: docker build -t wassim-devops-image:latest .
            args:
              chdir: /opt/kubernetes

          - name: create tag to image
            command: docker tag wassim-devops-image wassim97/wassim-devops-image

          - name: push image on to dockerhub
            command: docker push wassim97/wassim-devops-image

          - name: remove docker images from ansible server
            command: docker rmi wassim-devops-image:latest wassim97/wassim-devops-image
            ignore_errors: yes
